FROM node:16-alpine

WORKDIR /app



# Copy only package.json and package-lock.json first for better caching
COPY frontend/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of your frontend source code
COPY frontend/ ./

# Start the development server and bind to all interfaces
CMD ["npm", "start", "--"]

